### ISSUE TITLE
Compile error when using ScalaFutures

### ISSUE THREAD

**Issue by 14mr0n** [agido/pageobject#11]
When you use ScalaFutures of scala test in combination with WaitFor from pageobject, there is a type clash.

`trait Test extends WaitFor with ScalaFutures`

`Error:(15, 7) overriding type PatienceConfig in trait WaitFor, which equals org.pageobject.core.WaitFor.PatienceConfig;
 class PatienceConfig in trait AbstractPatienceConfiguration cannot be used here - classes can only override abstract types
trait Test extends WaitFor with ScalaFutures`

**Comment by drieks** [comment]
Hi,

you can change the order of `WaitFor` and `ScalaFutures` to workaround the problem.

I fixed the problem by removing the type alias `WaitFor.PatienceConfig`.
