### ISSUE TITLE
snapshot version mismatch

### ISSUE THREAD

**Issue by mb73** [agido/pageobject#15]
Sorry, if this is slightly out of topic. 

I find it difficult to always get the latest SNAPSHOT version. Looks like this is because maven-metadata.xml is not updated in Nexus. 
compare <lastUpdated>201705**01**071101</lastUpdated>in [maven-metadata.xml](https://oss.sonatype.org/content/repositories/snapshots/org/pageobject/core_2.11/0.3.0-SNAPSHOT/maven-metadata.xml) vs Tue May **02** 21:12:14 in [Directory Index](https://oss.sonatype.org/content/repositories/snapshots/org/pageobject/core_2.11/0.3.0-SNAPSHOT/).

May I ask how you upload the artifacts and if you have to trigger maven-metadata.xml generation/rebuild manually? Doesn't look like there is a daily generation/rebuild, because the last Upload is already two days ago and maven-metadata.xml is still outdated.

**Comment by drieks** [comment]
Hi,

We had the same problem a few days ago. (core and scalatest from different build dates).

As far as I know we have never manually triggered building maven-metadata.xml. This Script: https://github.com/agido/pageobject/blob/master/travis/upload.sh will upload the Snapshots, just calling `sbt core/publishSigned scalatest/publishSigned`.

This Script is called by travis, for example here: https://travis-ci.org/agido/pageobject/builds/228108100 (Only builds tagged with PUBLISH=true will do the upload)

If you look at the end of build log (https://travis-ci.org/agido/pageobject/jobs/228108101#L5225) you can see the script output.

I will try to figure out how to update the metadata.

**Comment by drieks** [comment]
It seems that the metadata is automatically updated but not very frequently..

https://oss.sonatype.org/content/repositories/snapshots/org/pageobject/core_2.12/0.3.0-SNAPSHOT/
Last snapshot:	Tue May 02 21:10:24 UTC 2017
Metadata update: Thu May 04 08:03:27 UTC 2017

**Comment by drieks** [comment]
A new build was uploaded, new timestamp is Thu May 04 08:39:20 UTC 2017.
I have manually deleted one of metadata files using sonatype repository manager:
https://oss.sonatype.org/#view-repositories;snapshots~browsestorage but it is not recreated yet and I found no way to do this. (I think this files are not maintained by nexus)

I found this: https://stackoverflow.com/questions/4878808/maven-metadata-xml-is-not-updated-when-deploying-to-nexus suggesting to set `updateReleaseInfo`.

It seems that sbt or ivy is not creating this file correctly: https://stackoverflow.com/questions/16734190/nexus-doesnt-update-metadata-for-snapshot

I'm trying to add https://github.com/arktekk/sbt-aether-deploy to the build to fix this.

**Comment by drieks** [comment]
@mb73 I deleted all old snapshot versions and the build uploaded new snapshots.

can you try to download the new snapshot version? thank you!

**Comment by mb73** [comment]
I will do so tomorrow, when I’m back in the office 😃 Thanks!

**Comment by mb73** [comment]
Perfect! 

In noticed the filenames of the artifacts have changed, e.g. 
from core_2.11-0.3.0-SNAPSHOT.jar 
to core_2.11-0.3.0-20170504.150107-1.jar. 
But that should be no problem.

**Comment by drieks** [comment]
Yes, this is the maven way. maven-metadata.xml is also used by maven.

Ivy (used by sbt) is using `core_2.11-0.3.0-SNAPSHOT.jar` and no maven-metadata.xml.

(Compare for example this directory here: https://oss.sonatype.org/content/repositories/snapshots/org/springframework/session/spring-session-data-redis/2.0.0.BUILD-SNAPSHOT/)

It seems that when using the ivy way the problem can occur that two different snapshots builds of `core` and `scalatest` are used that are not binary compatible.
