### ISSUE TITLE
command not found: log

### ISSUE THREAD

**Issue by mb73** [agido/pageobject#18]
Since I updated today my 0.3 snapshot, my tests do not work anymore on Firefox and IE. Chrome is still fine though.

Error message on Firefox:
org.openqa.selenium.UnsupportedCommandException: POST /session/0f39b428-97da-4e0f-8dd2-4d3aa86e8a4d/log did not match a known command

Error message on IE11:
org.openqa.selenium.WebDriverException: Command not found: POST /session/d430ef28-66e2-4a85-87fe-eb4c7f1345d2/log

Is this “log” something you added recently?

I'm using the latest webdrivers, by the way:

GeckoDriver: Version 0.16.1 (win64) 
https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-win64.zip

InternetExplorerDriver: Version 3.4.0  
https://selenium-release.storage.googleapis.com/3.4/IEDriverServer_x64_3.4.0.zip

**Comment by drieks** [comment]
Not added recently but I enabled the command logging feature. As a Workaround you can add an environment variable TRACE_REMOTE_WEB_DRIVER=false.

**Comment by mb73** [comment]
Thanks for the really quick answer :) it's still the same, though. 

![image](https://cloud.githubusercontent.com/assets/22412208/25738562/1fbb2a80-317e-11e7-9432-781e1f26820d.png)

**Comment by drieks** [comment]
I started a new snapshot build without this. I will add firefox to the travis test build to prevent this in the future.

**Comment by drieks** [comment]
The new snapshot is available!

**Comment by drieks** [comment]
* I have added geckodriver to the travis test build
* `TRACE_REMOTE_WEB_DRIVER=false` should work now for local drivers
* only for chrome `log` will be called to dump the browser console to the test log file
* a new snapshot is available

@mb73 please let me know if this is now working for you :smiley:

**Comment by mb73** [comment]
works (without having to set TRACE_REMOTE_WEB_DRIVER=false)
Thanks you!
