### ISSUE TITLE
FIREFOX_LIMIT=0 has no effect

### ISSUE THREAD

**Issue by mb73** [agido/pageobject#23]
- For CHROME_LIMIT=0 the tests do not run with Chrome.
- For IE_LIMIT=0 the tests do not run with IE.
- But for FIREFOX_LIMIT=0 the tests do still run with Firefox, bug?

**Comment by drieks** [comment]
Hi,

yes I think this is a bug. I will have a look. Did you specify `-Dwebdriver.gecko.path=...`?

**Comment by drieks** [comment]
because the webdriver path is using 'gecko' `GECKO_LIMIT=0` should work. I will fix this that `FIREFOX_LIMIT` will be used.

**Comment by drieks** [comment]
a new snapshot is available
